containers:
    vaultwarden:
    # The next 5 settings override the global settings for this container.
      ntfy_tags: closed_lock_with_key  
      ntfy_priority: 5
      ntfy_topic: security
      attachment_lines: 20     
      notification_cooldown: 10  
      keywords:
        - regex: (username|password).*incorrect   # Use regex expressions when you need them
        - login
      keywords_with_attachment:                   # send a file with the last log lines. 
        - critical
    audiobookshelf:
      keywords:
        - requested download
        - failed login

    # Just leave the them blank if global keywords are enough
    nextcloud:
    immich_server:


global_keywords:
  keywords:
    - segfault
    - panic
  keywords_with_attachment:
    - fatal

notifications:                       
  # At least one of the two (Ntfy/Apprise) is required.
  ntfy:
    url: http://your-ntfy-server    # Required. The URL of your Ntfy instance
    topic: loggifly.                # Required. the topic for Ntfy
    token: ntfy-token               # In case you need authorization 
    priority: 3                     # Ntfy priority (1-5)
    tags: kite,mag                  # Ntfy tags/emojis 
  apprise:
    url: "discord://webhook-url"    # Any Apprise-compatible URL (https://github.com/caronc/apprise/wiki)
  
settings:          
  log_level: INFO               # DEBUG, INFO, WARNING, ERROR
  notification_cooldown: 5      # Seconds between alerts for same keyword (per container)
  attachment_lines: 20          # Number of Lines to include in log attachments
  multi_line_entries: true      # Detect multi-line log entries
  disable_restart: false        # Disable restart when a config change is detected 
  disable_start_message: false  # Suppress startup notification
  disable_shutdown_message: false  # Suppress shutdown notification
  disable_restart_message: false   # Suppress config reload notification
