containers:
    audiobookshelf:
        - user
    nextcoud:
       - file
global-keywords:
  attachment:
    - error
  normal:
    - login


ntfy:
  url: "http://192.168.178.184:8282"
  topic: "logsend"
  token: "token"

settings:
  log-level: INFO
